version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/MessageProcessor.Worker"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/MessageProcessor.Tests"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/tools/ServiceBus.Spammer"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/greetings-api"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/greetings-api"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/MessageProcessor.Worker"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/tools/ServiceBus.Spammer"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
